sudo: required

language: node_js
node_js:
  - '8'

cache:
  directories:
    - ~/.npm
    - ~/.cache
    - ~/.meteor/
    - node_modules
    - $TRAVIS_BUILD_DIR/LesionTracker/node_modules

services:
  - docker
  - mongodb

env:
  global:
    tar: bsdtar
    LANG: en_US.UTF-8
    LC_ALL: en_US.UTF-8
    ORTHANC_IMG: casaper/orthanc-examples:0.3
    ORTHANC_NAME: orthanc_container
    L_T_PATH:  $TRAVIS_BUILD_DIR/LesionTracker
    METEOR_EX: $HOME/.meteor/meteor
    CYPRESS_EX: $TRAVIS_BUILD_DIR/LesionTracker/node_modules/.bin/cypress
    METEOR_PACKAGE_DIRS: $TRAVIS_BUILD_DIR/Packages
    ORTHANC_URL: http://orthanc:orthanc@127.0.0.1:8042
    MONGO_URL: mongodb://meteor:test@127.0.0.1:27017/ohif?authSource=admin
    ROOT_URL: http://127.0.0.1:3000
    PORT: 3000
    CYPRESS_ORTHANC_URL: $ORTHANC_URL
    CYPRESS_MONGO_URL: $MONGO_URL
    CYPRESS_MONGO_DUMP_PATH: $MONGO_DUMP_PATH
    CYPRESS_ROOT_URL: $ROOT_URL

script:
  - test/startup_meteor_and_tests.sh
