version: '3.6'
services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: meteor
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: hoif

  orthanc:
    image: casaper/orthanc-examples:0.3
    ports:
      - 4242:4242
      - 8042:8042
