version: '3.6'
services:
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"

  lesiontracker:
    build:
      context: .
      dockerfile: ./lesion_tracker.dockerfile
    ports:
      - "3001:3000"
    links:
      - mongo
      - sampledata
    environment:
      - MONGO_URL=mongodb://mongo:27017/ohif
      - METEOR_PACKAGE_DIRS=../Packages
    extra_hosts:
      - "pacsIP:192.168.1.11"
    volumes:
      - ./dockersupport/lesion_tracker_app.json:/app/app.json

  sampledata:
    image: jodogne/orthanc-plugins
    ports:
      - 4242:4242
      - 8042:8042