---
  servers: 
    dicomWeb: 
      - 
        name: "Orthanc"
        wadoUriRoot: "http://orthanc:8042/wado"
        qidoRoot: "http://orthanc:8042/dicom-web"
        wadoRoot: "http://orthanc:8042/dicom-web"
        qidoSupportsIncludeField: false
        imageRendering: "wadouri"
        thumbnailRendering: "wadors"
        requestOptions: 
          auth: "orthanc:orthanc"
          logRequests: true
          logResponses: false
          logTiming: true
  defaultServiceType: "dicomWeb"
  dropCollections: true
  public: 
    verifyEmail: false
    ui: 
      studyListFunctionsEnabled: true
      leftSidebarOpen: false
      displaySetNavigationLoopOverSeries: false
      displaySetNavigationMultipleViewports: true
      autoPositionMeasurementsTextCallOuts: "TRLB"
  proxy: 
    enabled: true

